version: '3.7'
services:
  api:
    container_name: nest_api
    build:
      context: .
    ports:
      - 80:3000
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: user
      DATABASE_DATABASE: database
      DATABASE_PASS: my_pwd
    depends_on:
      - db
  db:
    image: mysql:5
    container_name: feegow_challenge_db
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: my_pwd
    ports:
      - "8092:3306"
